version: '2'

services:
  master:
    build: .
    environment:
      - TARGET_HOST=http://www.kenlo.com.br
      - LOCUST_MODE=master
    ports:
      - 8089:8089
  worker-1:
    build: .
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER=master
    ports:
      - 5557:5557
    links:
      - master
  worker-2:
    build: .
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER=master
    ports:
      - 5558:5558
    links:
      - master